/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "1095de24a805fb4ef0fcc7569b47b5f366cebccf"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
